### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by BadHumanX** [ch4xm/spicetify-song-views#1]
I have installed the plugin, but it doest not seem to work. I cannot even see it in the columns. and where does it get the playcount from? It will be nice if I can connect it with LASTFM

**Comment by ch4xm** [comment]
Hi, sorry for the issue, I have only tested the extension on my own machine. 

What does it show in the spotify console (you can access it by running spicetify enable-devtools in a terminal and pressing Ctrl + Shift + i)? 

As for your question, it simply gets the playcount from spotify's own playcount for a song, eg the playcounts column that show when you look at an album page on spotify. I don't have any plans for LastFM integration at the moment.

**Comment by ch4xm** [comment]
Whoops, I never updated the in the 'dist' folder, so you were likely using the way outdated version before I actually started working on the extension. Try downloading the new song-views.js file from dist and using that, hopefully it should work!

**Comment by BadHumanX** [comment]
> Whoops, I never updated the in the 'dist' folder, so you were likely using the way outdated version before I actually started working on the extension. Try downloading the new song-views.js file from dist and using that, hopefully it should work!

Am lost here. about downloading the song-views... and the entire message you wrote. am not familiar with github. can you update it and they i can go on specitify and upgrade from there maybe? or better can you use a gif maybe to demonstrate the usage of it. Please

**Comment by ch4xm** [comment]
Hi, I have added it to the marketplace; if you go to extensions and type "Spicetify Song Views" (you might have to press "load more"), it should show up and you should be able to directly add it to your spicetify. Hope this works!

**Comment by BadHumanX** [comment]
![Screenshot 2024-10-30 112327](https://github.com/user-attachments/assets/fa212ac8-78cf-476f-846a-bce2d02e54df)
Ok. I have reinstalled the extension.
I have opened my playlist
I cannot see the play count yet.

did I miss a step?

**Comment by ch4xm** [comment]
Try looking at another playlist, I don't think my extension works in the "Liked Songs" playlist at the moment.
